// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"time"
)

type Url struct {
	ID          int32
	OriginalUrl string
	ShortUrl    string
	CreatedAt   time.Time
}
